spring.application.name=interoperability-okta
spring.autoconfigure.exclude=net.devh.boot.grpc.server.autoconfigure.GrpcServerSecurityAutoConfiguration

spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME:interoperability_okta}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080
grpc.server.port=9090

cxf.path=/ws

jwt.secret=${JWT_SECRET:change-this-development-secret-change-this-development-secret}

app.use-public-api=${APP_USE_PUBLIC_API:false}
app.okta.domain=${OKTA_DOMAIN:}
app.okta.token=${OKTA_API_TOKEN:}

spring.graphql.graphiql.enabled=true
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true